version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-belajar
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: belajar_spring
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin-belajar
    restart: always
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"

volumes:
  mysql_data: